events {}

http {

    upstream autorent_servers {

        server app1:8080;
        server app2:8080;
        server app3:8080;

    }

    server {

        listen 80;

        location / {

            proxy_pass http://autorent_servers;

        }
    }
}